# Configuration template for the mosquitto user configuration
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf

listener 0 ${RUN}/mosquitto/mosquitto.socket 

# We rely on socket permissions here. This needs to be changed if mosquitto is 
# listening on a port.
allow_anonymous true

pid_file ${RUN}/mosquitto/mosquitto.pid

persistence true
persistence_location ${STATE}/mosquitto

log_dest file ${LOG}/mosquitto/mosquitto.log

