etc/mosquitto/ca_certificates/README
etc/mosquitto/certs/README
etc/mosquitto/conf.d/README
etc/mosquitto/mosquitto.conf
etc/mosquitto/*.example
usr/lib/systemd/system/mosquitto.service
usr/bin/mosquitto_passwd
usr/bin/mosquitto_ctrl
usr/lib/*/mosquitto_dynamic_security.so*
usr/sbin/mosquitto
debian/systemd.user/init usr/share/mosquitto/user/bin
debian/systemd.user/mosquitto.conf usr/share/mosquitto/user/config
debian/systemd.user/README-systemd-user.md usr/share/doc/mosquitto
