etc/mosquitto/ca_certificates/README
etc/mosquitto/certs/README
etc/mosquitto/conf.d/README
etc/mosquitto/mosquitto.conf
etc/mosquitto/*.example
usr/bin/mosquitto_ctrl
usr/bin/mosquitto_db_dump
usr/bin/mosquitto_passwd
usr/bin/mosquitto_signal
usr/sbin/mosquitto
usr/lib/systemd/system/mosquitto.service
usr/lib/${DEB_HOST_MULTIARCH}/mosquitto_*.so usr/lib/${DEB_HOST_MULTIARCH}/mosquitto
debian/systemd.user/init usr/share/mosquitto/user/bin
debian/systemd.user/mosquitto.conf usr/share/mosquitto/user/config
debian/systemd.user/README-systemd-user.md usr/share/doc/mosquitto
